language: objective-c
osx_image: xcode9.3

script:
- xcodebuild clean test -project test/test.xcodeproj -scheme test -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.3' CODE_SIGNING_REQUIRED=NO
